import {renderPortal} from '/shared/react-ui.js';
import {api,logout,session,download} from '/shared/api.js';
import {esc,list,icon,notify,modal,errorPanel} from '/shared/ui.js';
import {openBatchUpload} from '/shared/upload-batch.js';
import {openArchiveUpload} from '/shared/archive-upload.js';

const availablePages=new Set(['home','guide','case','faq','reviews']);
const initialURL=new URL(location.href);
const state={page:availablePages.has(initialURL.searchParams.get('page'))?initialURL.searchParams.get('page'):'home',tab:['home','documents','messages'].includes(initialURL.searchParams.get('tab'))?initialURL.searchParams.get('tab'):'home',case:null,error:null,publicData:{},publicError:null,demoMode:false,startProfile:'demo',freshTesting:false,loadingCase:false,authEpoch:0};
const path=(suffix='')=>`/cases/${encodeURIComponent(state.case.id)}${suffix}`;
function clearUnavailableCase(){state.authEpoch+=1;state.case=null;state.error=null;state.loadingCase=false;state.page='case';state.tab='home';document.querySelector('#dialog')?.close();const url=new URL(location.href);url.searchParams.delete('case');url.searchParams.set('page','case');url.searchParams.set('tab','home');history.replaceState({},'',url);render();}
async function load(){if(session.user?.role!=='client')return;const epoch=state.authEpoch;state.loadingCase=true;render();try{let next;if(state.case)next=await api(path());else{const response=await api('/cases');const cases=list(response.cases||response);next=cases[0]?await api('/cases/'+encodeURIComponent(cases[0].id)):null;}if(epoch!==state.authEpoch)return;state.case=next;state.error=null;}catch(error){if(epoch===state.authEpoch){if([403,404].includes(error.status))clearUnavailableCase();else state.error=error;}}finally{if(epoch===state.authEpoch){state.loadingCase=false;render();}}}
async function loadPublic(){try{state.publicData=await api('/portal/public');state.publicError=null;}catch(error){state.publicError=error;}render();}
function navigate(page,tab){state.page=availablePages.has(page)?page:'home';if(tab)state.tab=tab;const url=new URL(location.href);url.searchParams.set('page',state.page);if(state.page==='case')url.searchParams.set('tab',state.tab);else url.searchParams.delete('tab');history.pushState({},'',url);render();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
async function login(credentials){const result=await api('/auth/login',{method:'POST',body:{...credentials,username:String(credentials.username||'').trim()}});if(result.user?.role!=='client'){try{await api('/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+result.token}});}catch{}throw new Error('고객 계정으로 로그인해 주세요. 직원 업무공간은 별도로 이용해 주세요.');}state.authEpoch+=1;session.token=result.token;session.user=result.user;sessionStorage.setItem('debtoff-token',result.token);state.case=null;state.error=null;await load();}
async function signOut(){state.authEpoch+=1;state.case=null;state.error=null;state.loadingCase=false;session.user=null;render();await logout();session.user=null;render();}
async function handoff(message){const epoch=state.authEpoch;const result=await api('/portal/handoff',{method:'POST',body:{case_id:state.case.id,message,expected_version:state.case.version}});if(epoch!==state.authEpoch)return;state.case=result.case||result;render();}
async function readNotification(id){const epoch=state.authEpoch;const result=await api(path('/notifications/'+encodeURIComponent(id)+'/read'),{method:'POST',body:{expected_version:state.case.version}});if(epoch!==state.authEpoch)return;state.case=result.case||result;render();}
async function applyForConsultation(values){const epoch=state.authEpoch;const result=await api('/portal/applications',{method:'POST',body:values});if(epoch!==state.authEpoch)return;state.case=result.case||result;state.error=null;state.loadingCase=false;navigate('case','home');notify('상담 신청을 접수했습니다. 담당 직원 또는 변호사가 세부상담 방법을 안내합니다.');}
function render(){renderPortal({state,user:session.user,request:api,onNavigate:navigate,onLogin:login,onLogout:signOut,onApply:applyForConsultation,onDownloadTesting:()=>download('/portal/testing-materials'+(state.case?.id?'?case_id='+encodeURIComponent(state.case.id):''),'연습자료.zip'),onRefreshPublic:loadPublic,onHandoff:handoff,onReadNotification:readNotification,errorHtml:state.error?errorPanel(state.error):''});}
function upload(requestId){const epoch=state.authEpoch;return openBatchUpload({caseData:state.case,requestId,role:'client',isCurrent:()=>epoch===state.authEpoch&&session.user?.role==='client',onComplete:async updated=>{state.case=updated;await load();}});}
function uploadArchive(){const epoch=state.authEpoch;return openArchiveUpload({caseData:state.case,isCurrent:()=>epoch===state.authEpoch&&session.user?.role==='client',onComplete:async updated=>{state.case=updated;await load();}});}
document.addEventListener('click',async e=>{const tab=e.target.closest('[data-tab]');const action=e.target.closest('[data-action]');try{if(session.user?.role!=='client')return;if(tab){navigate('case',tab.dataset.tab);return;}if(!action||!['refresh','upload','upload-archive','download'].includes(action.dataset.action))return;action.disabled=true;if(action.dataset.action==='refresh')await load();if(action.dataset.action==='upload'&&state.case)upload(action.dataset.request);if(action.dataset.action==='upload-archive'&&state.case)uploadArchive();if(action.dataset.action==='download'&&state.case){const d=state.case.documents.find(x=>x.id===action.dataset.id);await download(path('/documents/'+encodeURIComponent(d.id)+'/download'),d.filename||d.name);}action.disabled=false;}catch(error){notify(error.message,'error');if(action)action.disabled=false;}});
document.addEventListener('submit',async e=>{if(e.target.id!=='message-form')return;e.preventDefault();if(session.user?.role!=='client'||!state.case)return;const epoch=state.authEpoch;const button=e.target.querySelector('[type=submit]');button.disabled=true;try{const text=new FormData(e.target).get('text');const result=await api(path('/messages'),{method:'POST',body:{text,expected_version:state.case.version}});if(epoch!==state.authEpoch)return;state.case=result.case||result;e.target.reset();notify('메시지를 전달했습니다.');render();document.querySelector('#messages')?.scrollTo(0,100000);}catch(error){notify(error.message,'error');}finally{button.disabled=false;}});
window.addEventListener('session-expired',()=>{state.authEpoch+=1;session.user=null;state.case=null;state.error=null;state.loadingCase=false;render();});
window.addEventListener('popstate',()=>{const query=new URLSearchParams(location.search);state.page=availablePages.has(query.get('page'))?query.get('page'):'home';state.tab=['home','documents','messages'].includes(query.get('tab'))?query.get('tab'):'home';render();});
// Customer-safe requests arrive in this frontend without revealing internal
// rules, model prompts, findings, or draft documents.
let refreshPending=false,renderPending=false;
setInterval(async()=>{
  if(refreshPending||!session.user||document.hidden||document.querySelector('dialog[open]'))return;
  refreshPending=true;const epoch=state.authEpoch;
  try{
    let next;if(state.case)next=await api(path());else{const response=await api('/cases');const cases=list(response.cases||response);next=cases[0]?await api('/cases/'+encodeURIComponent(cases[0].id)):null;}
    if(epoch!==state.authEpoch)return;
    if(JSON.stringify(next)!==JSON.stringify(state.case)){state.case=next;renderPending=true;}
    const composing=document.querySelector('#message-text')?.value.trim();
    if(renderPending&&!composing&&!document.activeElement?.matches('input,textarea,select')){render();renderPending=false;}
  }catch(error){if(epoch===state.authEpoch&&[403,404].includes(error.status))clearUnavailableCase();}finally{refreshPending=false;}
},7000);
async function restoreSession(){if(!session.token)return;const epoch=state.authEpoch;try{const result=await api('/auth/me');if(epoch!==state.authEpoch)return;if((result.user||result).role!=='client'){await logout();session.user=null;return;}session.user=result.user||result;await load();}catch{session.user=null;session.token=null;sessionStorage.removeItem('debtoff-token');}render();}
render();
void Promise.allSettled([loadPublic(),restoreSession(),Promise.all([api('/health').catch(()=>({})),api('/auth/config').catch(()=>({}))]).then(([health,config])=>{state.startProfile=config.start_profile||health.start_profile||'demo';state.demoMode=Boolean(config.allow_demo_shortcuts??health.demo_mode)||Boolean(state.startProfile==='fresh'&&config.local_test_accounts);state.freshTesting=Boolean((config.demo_mode??health.demo_mode)&&state.startProfile==='fresh');render();})]);
