import React from 'react';
import PortalExperience from './PortalExperience.jsx';
import {consultationState,customerMatterLabel} from './portalCaseStatus.js';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {icon,brand,date,list,legalBasisLabel,readableText} from '../../shared/ui.js';
import {humanText} from '../../shared/structured.js';
import {calculationBlockerTitle} from '../../shared/legal-labels.js';
import {requestWithdrawn,requestNeedsUpload,requestScope,requestOptions,requestFeedback} from '../../shared/requests.js';

const stageNames={consultation:'세부 상담',consultation_waiting:'세부 상담 대기',collecting:'서류 준비·보완',extraction:'상담·서류 내용 추출',validation:'제출 자료 검증',ocr_verification:'추출값 검증',verification_waiting:'검증 재시도 필요',legal_analysis:'쟁점·계산 분석',lawyer_review:'변호사 검토 필요',drafting:'1차 문서 자동 작성',document_verification:'AI 문서 검토',human_review:'담당자 보완·승인',submission_ready:'제출 준비',submitted:'법원 제출 기록 완료',completed:'자동 검토 완료'};
const stepNames={waiting:'대기',running:'진행 중',completed:'완료',blocked:'보완 필요',review_required:'담당자 확인 필요',failed:'재확인 필요'};
const requestNames={fulfilled:'확인 완료',received:'제출 확인 중',validating:'제출 확인 중',processing:'제출 확인 중',requested:'제출 필요',missing:'제출 필요',needs_review:'추가 확인',needs_more:'다시 제출 필요',rejected:'다시 제출 필요',withdrawn:'요청 철회',cancelled:'요청 철회',superseded:'새 요청으로 변경'};
const roots=new Map();
let pipelineRoots=[];
const explanation=value=>humanText(typeof value==='string'?value:value?.message||value?.description||value?.reason||value?.title||'');
const safeURL=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
function Html({html,className='',as:Tag='span'}){return <Tag className={className} dangerouslySetInnerHTML={{__html:html}}/>;}
function Icon({name}){return <Html html={icon(name)} className="react-icon"/>;}
function Button({children,action,tab,secondary=false,...props}){return <button className={`button ${secondary?'secondary':''}`} data-action={action} data-tab={tab} {...props}>{children}</button>;}
function Pill({status,children}){const color=['fulfilled','completed','verified'].includes(status)?'green':['rejected','needs_more','blocked','lawyer_review','verification_waiting'].includes(status)?'orange':status==='running'?'blue':'gray';return <span className={`badge ${color}`}>{children}</span>;}
function Empty({title,detail}){return <div className="empty-state"><Icon name="check"/><strong>{title}</strong><p>{detail}</p></div>;}
function SourceLinks({sources}){return <div className="react-source-links">{list(sources).map((s,i)=>safeURL(s.url||s.source_url)?<a key={i} href={safeURL(s.url||s.source_url)} target="_blank" rel="noopener noreferrer">{s.title||s.locator||'공식 근거'} <Icon name="arrow"/></a>:null)}</div>;}

function RequestCard({request:r,compact=false}){
  const options=requestOptions(r),feedback=requestFeedback(r);
  return <article className={`request-item ${requestWithdrawn(r)?'withdrawn':''}`}><div className="row"><span className="document-icon"><Icon name="file"/></span><div style={{minWidth:0,flex:1}}><h3>{r.title}</h3></div><Pill status={r.status}>{r.no_longer_required?'이전 요청 보관':requestNames[r.status]||'확인 필요'}</Pill></div><p className="request-scope">{requestScope(r)||'기간·발급 범위 확인 중'}</p>{options&&<p className="small muted">발급 옵션 · {options}</p>}{feedback&&<div className={`callout ${['needs_more','rejected','missing'].includes(r.status)?'warning':'neutral'}`}><span>{feedback}</span></div>}{!compact&&<div className="request-detail"><strong>이 자료가 필요한 이유</strong><p>{r.reason||"사건 준비에 필요한 자료입니다. 안내된 기관과 기간을 확인해 주세요."}</p>{safeURL(r.issuance_url)&&<a href={safeURL(r.issuance_url)} target="_blank" rel="noopener noreferrer">공식 발급처 안내 <Icon name="arrow"/></a>}<details><summary>발급 방법과 확인할 내용</summary><p className="preserve-lines">{Array.isArray(r.steps)?r.steps.join('\n'):r.steps||'담당자에게 발급 방법을 문의해 주세요.'}</p>{r.not_proven&&<p>{r.not_proven}</p>}</details></div>}<div className="request-actions"><span className="small muted">{requestWithdrawn(r)?'이 자료는 더 이상 제출하지 않으셔도 됩니다.':r.due_date?'제출 안내일 · '+date(r.due_date):'준비가 어려우시면 담당자에게 알려주세요.'}</span>{!requestWithdrawn(r)?<Button secondary={compact} action="upload" data-request={r.id}><Icon name="upload"/>{['rejected','needs_more'].includes(r.status)?'다시 제출하기':requestNeedsUpload(r)?'제출하기':'자료 추가 제출'}</Button>:<Pill status={r.status}>{r.no_longer_required?'이전 요청 보관':requestNames[r.status]||'확인 중'}</Pill>}</div></article>;
}
function Notices({caseData:c}){
  const items=list(c.notifications).filter(n=>n.audience==='client'&&!n.resolved_at).slice(-4).reverse();
  if(!items.length)return null;
  return <section className="portal-notices card" aria-label="내 사건 안내" aria-live="polite"><div className="card-head"><h2><Icon name="bell"/>내 사건 안내</h2><Button secondary tab={consultationState(c)?"messages":"documents"}>{consultationState(c)?"상담 안내 확인":"보완할 서류 확인"}</Button></div><div className="card-body">{items.map(n=><div className="list-item" key={n.id}><strong>{n.title||'자료 확인 안내'}</strong><p>{n.message||n.body||n.reason}</p><p className="small muted">{date(n.created_at,true)}</p></div>)}</div></section>;
}
function Contact({caseData:c}){return <section className="card portal-contact"><div className="card-head"><h2>함께하는 담당자</h2></div><div className="card-body"><div className="contact-person"><span className="avatar"><Icon name="user"/></span><div><strong>{c.assigned_to||'담당 직원'}</strong><p>개인회생 사건 담당</p></div></div><p>혼자 알아보느라 애쓰지 않으셔도 됩니다.<br/>준비하며 궁금한 점을 편하게 남겨 주세요.</p><Button secondary tab="messages"><Icon name="message"/>담당자에게 문의</Button></div></section>;}
function Journey({caseData:c}){
  const consultation=consultationState(c);
  const steps=consultation?['상담 신청 접수','담당자 세부상담','자료 준비']:['자료 수집','신청 준비','법원 제출','보정','개시결정','인가','변제 중','면책'];
  const actual=({'검증 중':'자료 수집','보정 대응':'보정','문서 작성 완료':'신청 준비','1차 문서 작성':'신청 준비','1차 문서 검토':'신청 준비','담당자 검토':'신청 준비','담당자 보완·승인':'신청 준비','제출 준비':'신청 준비','법원 제출':'법원 제출','검토 보류':list(c.requests).filter(r=>!requestWithdrawn(r)).every(r=>r.status==='fulfilled')?'신청 준비':'자료 수집'})[c.stage]||c.stage,index=consultation?consultation.step:Math.max(0,steps.indexOf(actual));
  const reference=customerMatterLabel(c)||consultation?.label||c.stage||'상담 접수';
  return <section className="card progress-card"><div className="card-head"><div><div className="overline">YOUR PROGRESS</div><h2>{consultation?'담당자와 상담을 준비하고 있습니다.':'조금씩, 앞으로 나아가고 있어요.'}</h2></div><Pill status={consultation?'waiting':'running'}>{consultation?.label||c.stage}</Pill></div><div className="card-body"><div className={`steps ${consultation?'consultation-steps':''}`}>{steps.map((s,i)=><div key={s} className={`step ${i<index?'done':i===index?'active':''}`}><span className="step-number">{i<index?<Icon name="check"/>:i+1}</span>{s}</div>)}</div><p className="small muted">{consultation?'직원·변호사가 세부상담을 진행하고 상담 기록을 정리한 뒤 필요한 서류를 안내합니다.':'보정은 요청 시 진행되며 사건에 따라 순서가 달라질 수 있습니다.'}</p><div className="portal-progress"><span>{[c.court_name,reference].filter(Boolean).join(' · ')}</span><span>담당자 {c.assigned_to||'배정 중'}</span></div></div></section>;
}
function ArchiveEntry(){return <section className="portal-bulk-upload" aria-label="압축파일 일괄 제출"><span><Icon name="folder"/></span><div><h2>서류가 여러 개라면, 한 번에 넣으세요.</h2><p>ZIP 안의 내용을 읽어 알맞은 요청에 연결합니다. 파일 이름은 바꾸지 않아도 됩니다.</p></div><Button action="upload-archive"><Icon name="upload"/>한 번에 넣기</Button></section>;}
function PortalDocuments({caseData:c}){
  const requests=list(c.requests).filter(r=>!requestWithdrawn(r)),withdrawn=list(c.requests).filter(requestWithdrawn);
  return <><div className="portal-greeting portal-page-banner"><img src="/shared/images/warm-architecture.jpg" alt="햇살이 닿은 따뜻한 색의 건축 기둥"/><div className="eyebrow">A LITTLE PREPARATION, A CLEARER PATH</div><h1>필요한 서류, 하나씩 준비해요.</h1><p>{consultationState(c)?"담당자의 세부상담 후 필요한 서류와 발급 범위를 안내합니다.":"어디서 발급하고, 어느 기간이 필요한지 확인한 뒤 올려 주세요."}</p></div><Notices caseData={c}/><ArchiveEntry/><div className="portal-columns"><section className="card"><div className="card-head"><h2>요청받은 자료 <span className="small muted">{requests.length}</span></h2><Button secondary action="refresh"><Icon name="refresh"/>새로고침</Button></div><div className="card-body">{requests.map(r=><RequestCard key={r.id} request={r}/>)}{!requests.length&&<Empty title="현재 요청받은 자료가 없습니다"/>}{withdrawn.length>0&&<details className="portal-withdrawn"><summary>철회·변경된 요청 {withdrawn.length}건</summary>{withdrawn.map(r=><RequestCard key={r.id} request={r}/>)}</details>}</div></section><aside className="stack"><section className="card"><div className="card-head"><h2>내가 제출한 파일</h2></div><div className="card-body">{list(c.documents).map(d=><div className="file-row" key={d.id}><Icon name="file"/><div style={{minWidth:0,overflowWrap:'anywhere'}}><strong>{d.filename||d.name}</strong><small>{date(d.created_at||d.uploaded_at,true)}</small><button className="button subtle small" data-action="download" data-id={d.id}>파일 확인 <Icon name="download"/></button></div><Pill status={d.status}>{d.status==='verified'?'확인 완료':['rejected','needs_more'].includes(d.status)?'다시 확인 필요':'수신 완료'}</Pill></div>)}{!list(c.documents).length&&<Empty title="아직 제출한 파일이 없습니다"/>}<Button secondary action="upload"><Icon name="plus"/>다른 자료 제출</Button></div></section><Contact caseData={c}/><div className="callout neutral"><Icon name="info"/><p>모든 페이지와 글자가 잘 보이도록 올려 주세요. 부족하거나 잘못된 자료는 보완할 내용을 알려드립니다.</p></div></aside></div></>;
}
function PortalMessages({caseData:c}){
  return <><div className="portal-greeting portal-page-banner"><img src="/shared/images/quiet-horizon.jpg" alt="바다 위에 번지는 따뜻한 빛"/><div className="eyebrow">WE ARE HERE FOR YOU</div><h1>작은 궁금함도 남겨 주세요.</h1><p>준비가 막막한 순간에도, 담당자가 함께 살펴보겠습니다.</p></div><section className="card"><div className="card-head"><h2><Icon name="message"/>{c.assigned_to||'담당자'}와 대화</h2><Button secondary action="refresh"><Icon name="refresh"/>새로고침</Button></div><div className="card-body"><div className="message-list" id="messages">{list(c.messages).map((m,i)=><div key={m.id||i} className={`message-bubble ${m.role==='client'?'mine':''}`}><small>{m.role==='client'?'나':m.sender||'담당자'}</small>{m.text}<time>{date(m.created_at,true)}</time></div>)}{!list(c.messages).length&&<Empty title="어떤 점이 궁금하신가요?" detail="서류 준비나 사건 진행에 관한 질문을 남겨 주세요."/>}</div><form id="message-form" className="message-compose"><label className="sr-only" htmlFor="message-text">담당자에게 보낼 메시지</label><textarea id="message-text" name="text" placeholder="담당자에게 전달할 내용을 적어 주세요." required maxLength={4000}/><Button type="submit">보내기 <Icon name="arrow"/></Button></form></div></section></>;
}
function PortalApp(props){
  const {state,user,errorHtml}=props,c=state.case;
  const consultation=consultationState(c),matterLabel=customerMatterLabel(c);
  const pending=list(c?.requests).filter(requestNeedsUpload),active=list(c?.requests).filter(request=>!requestWithdrawn(request)),done=active.filter(request=>request.status==='fulfilled').length;
  const content=state.error?<Html as="div" html={errorHtml}/>:state.loadingCase?<Empty title="내 사건을 확인하고 있습니다"/>:!c?<Empty title="아직 연결된 사건이 없습니다" detail="담당 사무소에 계정과 사건 연결을 요청해 주세요."/>:<><div className="private-workspace-heading"><span className="eyebrow">MY CASE, EVERY STEP</span><h1>{c.client_name}님의 사건</h1><p>{[c.court_name,matterLabel,'담당자 '+(c.assigned_to||'배정 중')].filter(Boolean).join(' · ')}</p></div><nav className="private-workspace-tabs" aria-label="내 사건 메뉴">{[['home','진행 상황'],['documents','제출 서류'],['messages','담당자 문의']].map(([id,title])=><button key={id} className={state.tab===id?'active':''} data-tab={id}>{title}</button>)}</nav>{state.tab==='documents'?<PortalDocuments caseData={c}/>:state.tab==='messages'?<PortalMessages caseData={c}/>:<><div className="private-next-action"><Icon name={consultation?'message':pending.length?'file':'check'}/><div><span className="eyebrow">지금 준비할 일</span><h2>{consultation?consultation.title:pending.length?'필요한 서류 '+pending.length+'건을 확인해 주세요.':'보내주신 자료를 차근차근 확인하고 있어요.'}</h2><p>{consultation?consultation.description:pending.length?'안내된 기관과 기간을 확인한 뒤 제출해 주세요.':'다음 단계나 추가 요청이 생기면 알림으로 안내합니다.'}</p></div><Button secondary tab={consultation?"messages":"documents"}>{consultation?"상담 안내 확인":"서류 확인"} <Icon name="arrow"/></Button></div><Notices caseData={c}/><Journey caseData={c}/><div className="portal-columns"><section className="card"><div className="card-head"><div><h2>{consultation?"상담 후 준비할 자료":"준비할 자료"}</h2>{!consultation&&<p className="small muted">확인 완료 {done} / {active.length}건</p>}</div><Button secondary tab="documents">전체 보기</Button></div><div className="card-body">{pending.slice(0,3).map(request=><RequestCard key={request.id} request={request} compact/>)}{!pending.length&&<Empty title={consultation?"세부상담 후 필요한 자료를 안내합니다":"현재 새로 제출할 자료가 없습니다"} detail={consultation?"우선 담당자의 상담 안내를 기다려 주세요.":"다음 단계나 필요한 자료가 생기면 안내합니다."}/>}</div></section><aside className="portal-aside"><Contact caseData={c}/></aside></div></>}</>;
  return <PortalExperience {...props}>{content}</PortalExperience>;
}

function rootFor(node){if(!roots.has(node))roots.set(node,createRoot(node));return roots.get(node);}
export function clearWorkspace(){pipelineRoots.forEach(r=>r.unmount());pipelineRoots=[];for(const root of roots.values())root.unmount();roots.clear();}
export function renderPortal(props){flushSync(()=>rootFor(document.querySelector('#app')).render(<PortalApp {...props}/>));}
